context('body shop test dev', () => {
  specify('first dev test', () => {
    cy.visit('https://dev-consultant.thebodyshop.com/en-us/myshop/danitaylor/enrol')
    cy.wait(3000)
    cy.get('.welcome__footer > .button').click({ force: true})
    cy.get('.native-input').focus().type('riya99986@gmail.com')
    cy.get('.enrolment__button').click({ force: true})
    cy.get('form > .input-group > .ion-no-padding > .input-suffix-icon > .sc-ion-input-md-h > .native-input').type('Pass@1234')
    cy.get('.ion-text-capitalize').click({ force: true})
    // cy.get(':nth-child(1) > .ion-no-padding').type('Riya')
    // cy.get('.step-two > :nth-child(4) > .ion-no-padding').type('Singh')
    // cy.get('.ssn-input').type('121212122')
    cy.get('[name="day"]').focus().select('31')
    cy.get('[name="month"]').focus().select('Oct')
    cy.get('[name="year"]').select('1999')
    cy.get('.enrolment__button')
    cy.contains('Next').click({ force: true})
    cy.get('.enrolment__buttons > :nth-child(2)')
    cy.contains('Next').click({ force: true})
    cy.get(':nth-child(2) > .starter-kit-card__content > .starter-kit-card__buttons > .md').click({ force: true})
    cy.get('.add-on-continue__button')
    cy.contains('Next').click({ force: true})
    
  })
})